//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationTemplate.Web.MLWSUserValidations {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserInformation", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class UserInformation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PublicNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CultureField;
        
        private System.Guid UserGuidField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string PublicName {
            get {
                return this.PublicNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PublicNameField, value) != true)) {
                    this.PublicNameField = value;
                    this.RaisePropertyChanged("PublicName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Culture {
            get {
                return this.CultureField;
            }
            set {
                if ((object.ReferenceEquals(this.CultureField, value) != true)) {
                    this.CultureField = value;
                    this.RaisePropertyChanged("Culture");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.Guid UserGuid {
            get {
                return this.UserGuidField;
            }
            set {
                if ((this.UserGuidField.Equals(value) != true)) {
                    this.UserGuidField = value;
                    this.RaisePropertyChanged("UserGuid");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MLWSUserValidations.UserValidationsSoap")]
    public interface UserValidationsSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento IDSession del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ValidateSession", ReplyAction="*")]
        WebApplicationTemplate.Web.MLWSUserValidations.ValidateSessionResponse ValidateSession(WebApplicationTemplate.Web.MLWSUserValidations.ValidateSessionRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento IDSession del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMessages", ReplyAction="*")]
        WebApplicationTemplate.Web.MLWSUserValidations.GetMessagesResponse GetMessages(WebApplicationTemplate.Web.MLWSUserValidations.GetMessagesRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento userMLD del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserName", ReplyAction="*")]
        WebApplicationTemplate.Web.MLWSUserValidations.GetUserNameResponse GetUserName(WebApplicationTemplate.Web.MLWSUserValidations.GetUserNameRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Guid del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ValidateGuid", ReplyAction="*")]
        WebApplicationTemplate.Web.MLWSUserValidations.ValidateGuidResponse ValidateGuid(WebApplicationTemplate.Web.MLWSUserValidations.ValidateGuidRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Guid del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserInformationByGUID", ReplyAction="*")]
        WebApplicationTemplate.Web.MLWSUserValidations.GetUserInformationByGUIDResponse GetUserInformationByGUID(WebApplicationTemplate.Web.MLWSUserValidations.GetUserInformationByGUIDRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento authCode del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserInformationAppByGUID", ReplyAction="*")]
        WebApplicationTemplate.Web.MLWSUserValidations.GetUserInformationAppByGUIDResponse GetUserInformationAppByGUID(WebApplicationTemplate.Web.MLWSUserValidations.GetUserInformationAppByGUIDRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidateSessionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidateSession", Namespace="http://tempuri.org/", Order=0)]
        public WebApplicationTemplate.Web.MLWSUserValidations.ValidateSessionRequestBody Body;
        
        public ValidateSessionRequest() {
        }
        
        public ValidateSessionRequest(WebApplicationTemplate.Web.MLWSUserValidations.ValidateSessionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ValidateSessionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string IDSession;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string IPMac;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string URLSite;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string idCompany;
        
        public ValidateSessionRequestBody() {
        }
        
        public ValidateSessionRequestBody(string IDSession, string IPMac, string URLSite, string idCompany) {
            this.IDSession = IDSession;
            this.IPMac = IPMac;
            this.URLSite = URLSite;
            this.idCompany = idCompany;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidateSessionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidateSessionResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApplicationTemplate.Web.MLWSUserValidations.ValidateSessionResponseBody Body;
        
        public ValidateSessionResponse() {
        }
        
        public ValidateSessionResponse(WebApplicationTemplate.Web.MLWSUserValidations.ValidateSessionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ValidateSessionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ValidateSessionResult;
        
        public ValidateSessionResponseBody() {
        }
        
        public ValidateSessionResponseBody(string ValidateSessionResult) {
            this.ValidateSessionResult = ValidateSessionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMessagesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMessages", Namespace="http://tempuri.org/", Order=0)]
        public WebApplicationTemplate.Web.MLWSUserValidations.GetMessagesRequestBody Body;
        
        public GetMessagesRequest() {
        }
        
        public GetMessagesRequest(WebApplicationTemplate.Web.MLWSUserValidations.GetMessagesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMessagesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string IDSession;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string IPMac;
        
        public GetMessagesRequestBody() {
        }
        
        public GetMessagesRequestBody(string IDSession, string IPMac) {
            this.IDSession = IDSession;
            this.IPMac = IPMac;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMessagesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMessagesResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApplicationTemplate.Web.MLWSUserValidations.GetMessagesResponseBody Body;
        
        public GetMessagesResponse() {
        }
        
        public GetMessagesResponse(WebApplicationTemplate.Web.MLWSUserValidations.GetMessagesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMessagesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetMessagesResult;
        
        public GetMessagesResponseBody() {
        }
        
        public GetMessagesResponseBody(string GetMessagesResult) {
            this.GetMessagesResult = GetMessagesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserName", Namespace="http://tempuri.org/", Order=0)]
        public WebApplicationTemplate.Web.MLWSUserValidations.GetUserNameRequestBody Body;
        
        public GetUserNameRequest() {
        }
        
        public GetUserNameRequest(WebApplicationTemplate.Web.MLWSUserValidations.GetUserNameRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserNameRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userMLD;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string URL;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int CompanyMLD;
        
        public GetUserNameRequestBody() {
        }
        
        public GetUserNameRequestBody(string userMLD, string URL, int CompanyMLD) {
            this.userMLD = userMLD;
            this.URL = URL;
            this.CompanyMLD = CompanyMLD;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserNameResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApplicationTemplate.Web.MLWSUserValidations.GetUserNameResponseBody Body;
        
        public GetUserNameResponse() {
        }
        
        public GetUserNameResponse(WebApplicationTemplate.Web.MLWSUserValidations.GetUserNameResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserNameResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetUserNameResult;
        
        public GetUserNameResponseBody() {
        }
        
        public GetUserNameResponseBody(string GetUserNameResult) {
            this.GetUserNameResult = GetUserNameResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidateGuidRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidateGuid", Namespace="http://tempuri.org/", Order=0)]
        public WebApplicationTemplate.Web.MLWSUserValidations.ValidateGuidRequestBody Body;
        
        public ValidateGuidRequest() {
        }
        
        public ValidateGuidRequest(WebApplicationTemplate.Web.MLWSUserValidations.ValidateGuidRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ValidateGuidRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Guid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string IDSession;
        
        public ValidateGuidRequestBody() {
        }
        
        public ValidateGuidRequestBody(string Guid, string IDSession) {
            this.Guid = Guid;
            this.IDSession = IDSession;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidateGuidResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidateGuidResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApplicationTemplate.Web.MLWSUserValidations.ValidateGuidResponseBody Body;
        
        public ValidateGuidResponse() {
        }
        
        public ValidateGuidResponse(WebApplicationTemplate.Web.MLWSUserValidations.ValidateGuidResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ValidateGuidResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ValidateGuidResult;
        
        public ValidateGuidResponseBody() {
        }
        
        public ValidateGuidResponseBody(bool ValidateGuidResult) {
            this.ValidateGuidResult = ValidateGuidResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserInformationByGUIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserInformationByGUID", Namespace="http://tempuri.org/", Order=0)]
        public WebApplicationTemplate.Web.MLWSUserValidations.GetUserInformationByGUIDRequestBody Body;
        
        public GetUserInformationByGUIDRequest() {
        }
        
        public GetUserInformationByGUIDRequest(WebApplicationTemplate.Web.MLWSUserValidations.GetUserInformationByGUIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserInformationByGUIDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Guid;
        
        public GetUserInformationByGUIDRequestBody() {
        }
        
        public GetUserInformationByGUIDRequestBody(string Guid) {
            this.Guid = Guid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserInformationByGUIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserInformationByGUIDResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApplicationTemplate.Web.MLWSUserValidations.GetUserInformationByGUIDResponseBody Body;
        
        public GetUserInformationByGUIDResponse() {
        }
        
        public GetUserInformationByGUIDResponse(WebApplicationTemplate.Web.MLWSUserValidations.GetUserInformationByGUIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserInformationByGUIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetUserInformationByGUIDResult;
        
        public GetUserInformationByGUIDResponseBody() {
        }
        
        public GetUserInformationByGUIDResponseBody(string GetUserInformationByGUIDResult) {
            this.GetUserInformationByGUIDResult = GetUserInformationByGUIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserInformationAppByGUIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserInformationAppByGUID", Namespace="http://tempuri.org/", Order=0)]
        public WebApplicationTemplate.Web.MLWSUserValidations.GetUserInformationAppByGUIDRequestBody Body;
        
        public GetUserInformationAppByGUIDRequest() {
        }
        
        public GetUserInformationAppByGUIDRequest(WebApplicationTemplate.Web.MLWSUserValidations.GetUserInformationAppByGUIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserInformationAppByGUIDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string authCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.Guid userGuid;
        
        public GetUserInformationAppByGUIDRequestBody() {
        }
        
        public GetUserInformationAppByGUIDRequestBody(string authCode, System.Guid userGuid) {
            this.authCode = authCode;
            this.userGuid = userGuid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserInformationAppByGUIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserInformationAppByGUIDResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApplicationTemplate.Web.MLWSUserValidations.GetUserInformationAppByGUIDResponseBody Body;
        
        public GetUserInformationAppByGUIDResponse() {
        }
        
        public GetUserInformationAppByGUIDResponse(WebApplicationTemplate.Web.MLWSUserValidations.GetUserInformationAppByGUIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserInformationAppByGUIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebApplicationTemplate.Web.MLWSUserValidations.UserInformation GetUserInformationAppByGUIDResult;
        
        public GetUserInformationAppByGUIDResponseBody() {
        }
        
        public GetUserInformationAppByGUIDResponseBody(WebApplicationTemplate.Web.MLWSUserValidations.UserInformation GetUserInformationAppByGUIDResult) {
            this.GetUserInformationAppByGUIDResult = GetUserInformationAppByGUIDResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UserValidationsSoapChannel : WebApplicationTemplate.Web.MLWSUserValidations.UserValidationsSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserValidationsSoapClient : System.ServiceModel.ClientBase<WebApplicationTemplate.Web.MLWSUserValidations.UserValidationsSoap>, WebApplicationTemplate.Web.MLWSUserValidations.UserValidationsSoap {
        
        public UserValidationsSoapClient() {
        }
        
        public UserValidationsSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserValidationsSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserValidationsSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserValidationsSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplicationTemplate.Web.MLWSUserValidations.ValidateSessionResponse WebApplicationTemplate.Web.MLWSUserValidations.UserValidationsSoap.ValidateSession(WebApplicationTemplate.Web.MLWSUserValidations.ValidateSessionRequest request) {
            return base.Channel.ValidateSession(request);
        }
        
        public string ValidateSession(string IDSession, string IPMac, string URLSite, string idCompany) {
            WebApplicationTemplate.Web.MLWSUserValidations.ValidateSessionRequest inValue = new WebApplicationTemplate.Web.MLWSUserValidations.ValidateSessionRequest();
            inValue.Body = new WebApplicationTemplate.Web.MLWSUserValidations.ValidateSessionRequestBody();
            inValue.Body.IDSession = IDSession;
            inValue.Body.IPMac = IPMac;
            inValue.Body.URLSite = URLSite;
            inValue.Body.idCompany = idCompany;
            WebApplicationTemplate.Web.MLWSUserValidations.ValidateSessionResponse retVal = ((WebApplicationTemplate.Web.MLWSUserValidations.UserValidationsSoap)(this)).ValidateSession(inValue);
            return retVal.Body.ValidateSessionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplicationTemplate.Web.MLWSUserValidations.GetMessagesResponse WebApplicationTemplate.Web.MLWSUserValidations.UserValidationsSoap.GetMessages(WebApplicationTemplate.Web.MLWSUserValidations.GetMessagesRequest request) {
            return base.Channel.GetMessages(request);
        }
        
        public string GetMessages(string IDSession, string IPMac) {
            WebApplicationTemplate.Web.MLWSUserValidations.GetMessagesRequest inValue = new WebApplicationTemplate.Web.MLWSUserValidations.GetMessagesRequest();
            inValue.Body = new WebApplicationTemplate.Web.MLWSUserValidations.GetMessagesRequestBody();
            inValue.Body.IDSession = IDSession;
            inValue.Body.IPMac = IPMac;
            WebApplicationTemplate.Web.MLWSUserValidations.GetMessagesResponse retVal = ((WebApplicationTemplate.Web.MLWSUserValidations.UserValidationsSoap)(this)).GetMessages(inValue);
            return retVal.Body.GetMessagesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplicationTemplate.Web.MLWSUserValidations.GetUserNameResponse WebApplicationTemplate.Web.MLWSUserValidations.UserValidationsSoap.GetUserName(WebApplicationTemplate.Web.MLWSUserValidations.GetUserNameRequest request) {
            return base.Channel.GetUserName(request);
        }
        
        public string GetUserName(string userMLD, string URL, int CompanyMLD) {
            WebApplicationTemplate.Web.MLWSUserValidations.GetUserNameRequest inValue = new WebApplicationTemplate.Web.MLWSUserValidations.GetUserNameRequest();
            inValue.Body = new WebApplicationTemplate.Web.MLWSUserValidations.GetUserNameRequestBody();
            inValue.Body.userMLD = userMLD;
            inValue.Body.URL = URL;
            inValue.Body.CompanyMLD = CompanyMLD;
            WebApplicationTemplate.Web.MLWSUserValidations.GetUserNameResponse retVal = ((WebApplicationTemplate.Web.MLWSUserValidations.UserValidationsSoap)(this)).GetUserName(inValue);
            return retVal.Body.GetUserNameResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplicationTemplate.Web.MLWSUserValidations.ValidateGuidResponse WebApplicationTemplate.Web.MLWSUserValidations.UserValidationsSoap.ValidateGuid(WebApplicationTemplate.Web.MLWSUserValidations.ValidateGuidRequest request) {
            return base.Channel.ValidateGuid(request);
        }
        
        public bool ValidateGuid(string Guid, string IDSession) {
            WebApplicationTemplate.Web.MLWSUserValidations.ValidateGuidRequest inValue = new WebApplicationTemplate.Web.MLWSUserValidations.ValidateGuidRequest();
            inValue.Body = new WebApplicationTemplate.Web.MLWSUserValidations.ValidateGuidRequestBody();
            inValue.Body.Guid = Guid;
            inValue.Body.IDSession = IDSession;
            WebApplicationTemplate.Web.MLWSUserValidations.ValidateGuidResponse retVal = ((WebApplicationTemplate.Web.MLWSUserValidations.UserValidationsSoap)(this)).ValidateGuid(inValue);
            return retVal.Body.ValidateGuidResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplicationTemplate.Web.MLWSUserValidations.GetUserInformationByGUIDResponse WebApplicationTemplate.Web.MLWSUserValidations.UserValidationsSoap.GetUserInformationByGUID(WebApplicationTemplate.Web.MLWSUserValidations.GetUserInformationByGUIDRequest request) {
            return base.Channel.GetUserInformationByGUID(request);
        }
        
        public string GetUserInformationByGUID(string Guid) {
            WebApplicationTemplate.Web.MLWSUserValidations.GetUserInformationByGUIDRequest inValue = new WebApplicationTemplate.Web.MLWSUserValidations.GetUserInformationByGUIDRequest();
            inValue.Body = new WebApplicationTemplate.Web.MLWSUserValidations.GetUserInformationByGUIDRequestBody();
            inValue.Body.Guid = Guid;
            WebApplicationTemplate.Web.MLWSUserValidations.GetUserInformationByGUIDResponse retVal = ((WebApplicationTemplate.Web.MLWSUserValidations.UserValidationsSoap)(this)).GetUserInformationByGUID(inValue);
            return retVal.Body.GetUserInformationByGUIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplicationTemplate.Web.MLWSUserValidations.GetUserInformationAppByGUIDResponse WebApplicationTemplate.Web.MLWSUserValidations.UserValidationsSoap.GetUserInformationAppByGUID(WebApplicationTemplate.Web.MLWSUserValidations.GetUserInformationAppByGUIDRequest request) {
            return base.Channel.GetUserInformationAppByGUID(request);
        }
        
        public WebApplicationTemplate.Web.MLWSUserValidations.UserInformation GetUserInformationAppByGUID(string authCode, System.Guid userGuid) {
            WebApplicationTemplate.Web.MLWSUserValidations.GetUserInformationAppByGUIDRequest inValue = new WebApplicationTemplate.Web.MLWSUserValidations.GetUserInformationAppByGUIDRequest();
            inValue.Body = new WebApplicationTemplate.Web.MLWSUserValidations.GetUserInformationAppByGUIDRequestBody();
            inValue.Body.authCode = authCode;
            inValue.Body.userGuid = userGuid;
            WebApplicationTemplate.Web.MLWSUserValidations.GetUserInformationAppByGUIDResponse retVal = ((WebApplicationTemplate.Web.MLWSUserValidations.UserValidationsSoap)(this)).GetUserInformationAppByGUID(inValue);
            return retVal.Body.GetUserInformationAppByGUIDResult;
        }
    }
}
