//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile el proyecto de Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Global {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Global() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Global", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Invalida la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ButtonClearFields.
        /// </summary>
        internal static string CssButtonClearFields {
            get {
                return ResourceManager.GetString("CssButtonClearFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ButtonClose.
        /// </summary>
        internal static string CssButtonClose {
            get {
                return ResourceManager.GetString("CssButtonClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ButtonNew.
        /// </summary>
        internal static string CssButtonNew {
            get {
                return ResourceManager.GetString("CssButtonNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ButtonPrint.
        /// </summary>
        internal static string CssButtonPrint {
            get {
                return ResourceManager.GetString("CssButtonPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ButtonSearch.
        /// </summary>
        internal static string CssButtonSearch {
            get {
                return ResourceManager.GetString("CssButtonSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There is not authenticated user in Macrolynk.
        /// </summary>
        internal static string MacrolynkUserNotAuthenticated {
            get {
                return ResourceManager.GetString("MacrolynkUserNotAuthenticated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The Macrolynk user does not exist in the application..
        /// </summary>
        internal static string MacrolynkUserNotExist {
            get {
                return ResourceManager.GetString("MacrolynkUserNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Missing web method attribute SoapHeader(CREDENTIALS).
        /// </summary>
        internal static string MissingSoapHeader {
            get {
                return ResourceManager.GetString("MissingSoapHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User {0} was created successfully.
        /// </summary>
        internal static string UserCreatedSuccessfully {
            get {
                return ResourceManager.GetString("UserCreatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Username.
        /// </summary>
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Session.IsAuthenticated = {0}; parameterTest = {1};.
        /// </summary>
        internal static string WebServiceTest {
            get {
                return ResourceManager.GetString("WebServiceTest", resourceCulture);
            }
        }
    }
}
