PRINT 'Carrera.sql...'
IF NOT EXISTS(
	SELECT * FROM INFORMATION_SCHEMA.COLUMNS
	WHERE TABLE_NAME = 'Carrera' AND COLUMN_NAME = 'FolioInicial'
)
BEGIN
	ALTER TABLE [Carrera]
	ADD [FolioInicial] INT NULL
END
GO
IF exists (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'FolioInicial' AND TABLE_NAME = 'Carrera'  AND IS_NULLABLE = 'YES')
BEGIN
	UPDATE [Carrera]
	SET [FolioInicial] = 1001
	WHERE [FolioInicial] IS NULL
END
GO

IF EXISTS(
	SELECT * FROM INFORMATION_SCHEMA.COLUMNS
	WHERE TABLE_NAME = 'Carrera' AND COLUMN_NAME = 'FolioInicial'
)
BEGIN	
	ALTER TABLE [Carrera] ALTER COLUMN [FolioInicial] INT NOT NULL
END
GO

IF NOT EXISTS(
	SELECT * FROM INFORMATION_SCHEMA.COLUMNS
	WHERE TABLE_NAME = 'Carrera' AND COLUMN_NAME = 'SiguienteFolio'
)
BEGIN
	ALTER TABLE [Carrera]
	ADD [SiguienteFolio] INT NULL
END
GO

IF exists (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'SiguienteFolio' AND TABLE_NAME = 'Carrera'  AND IS_NULLABLE = 'YES')
BEGIN
	UPDATE [Carrera]
	SET [SiguienteFolio] = 1001
	WHERE [SiguienteFolio] IS NULL
END
GO

IF EXISTS(
	SELECT * FROM INFORMATION_SCHEMA.COLUMNS
	WHERE TABLE_NAME = 'Carrera' AND COLUMN_NAME = 'SiguienteFolio' AND IS_NULLABLE = 'YES'
)
BEGIN
	ALTER TABLE [Carrera] ALTER COLUMN [SiguienteFolio] INT NOT NULL
END
GO

