PRINT 'Equipo.0.sql'

IF NOT EXISTS(
	SELECT * FROM INFORMATION_SCHEMA.COLUMNS
	WHERE TABLE_NAME = 'Equipo' AND COLUMN_NAME = 'Guid'
)
BEGIN
	EXEC(' ALTER TABLE [Equipo] ADD [Guid] UNIQUEIDENTIFIER NULL')
END
GO

IF EXISTS(
	SELECT * FROM INFORMATION_SCHEMA.COLUMNS
	WHERE TABLE_NAME = 'Equipo' AND COLUMN_NAME = 'Guid'
		AND IS_NULLABLE = 'YES'
)
BEGIN
	EXEC('UPDATE [Equipo] SET [Guid] = NEWID() WHERE [Guid] IS NULL')
	EXEC('ALTER TABLE [Equipo] ALTER COLUMN [Guid] UNIQUEIDENTIFIER NOT NULL')
END
GO

IF NOT EXISTS(
	SELECT * FROM INFORMATION_SCHEMA.COLUMNS
	WHERE TABLE_NAME = 'Equipo' AND COLUMN_NAME = 'Nombre'
)
BEGIN
	EXEC(' ALTER TABLE [Equipo] ADD [Nombre] VARCHAR(255) NULL')
END
GO

IF EXISTS(
	SELECT * FROM INFORMATION_SCHEMA.COLUMNS
	WHERE TABLE_NAME = 'Equipo' AND COLUMN_NAME = 'Nombre'
		AND IS_NULLABLE = 'YES'
)
BEGIN
	EXEC('UPDATE [Equipo] SET [Nombre] = '''' WHERE [Nombre] IS NULL')
	EXEC('ALTER TABLE [Equipo] ALTER COLUMN [Nombre] VARCHAR(255) NOT NULL')
END
GO
