IF exists (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'Pagado' AND TABLE_NAME = 'Participante'  AND IS_NULLABLE = 'NO')
BEGIN	
	ALTER TABLE [Participante]
	ALTER COLUMN [Pagado] bit NULL; 
END
GO

IF exists (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'Pagado' AND TABLE_NAME = 'Participante'  AND IS_NULLABLE = 'YES')
BEGIN	
	UPDATE [Participante]
	SET [Pagado] = null; 
END
GO

IF exists (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'Pagado' AND TABLE_NAME = 'Participante'  AND IS_NULLABLE = 'YES')
BEGIN	
	ALTER TABLE [Participante]
	DROP COLUMN [Pagado];
END
GO