PRINT 'User.sql'

IF EXISTS(/*Si existe la columna MacrolynkGUID en la tabla User*/
	SELECT * FROM INFORMATION_SCHEMA.COLUMNS
	WHERE TABLE_NAME = 'User'
	AND COLUMN_NAME = 'MacrolynkGUID'
)
BEGIN
	ALTER TABLE [User] DROP COLUMN MacrolynkGUID
END

IF NOT EXISTS(
	SELECT * FROM INFORMATION_SCHEMA.COLUMNS
	WHERE TABLE_NAME = 'User'
	AND COLUMN_NAME = 'Password'
)
BEGIN
	ALTER TABLE [User] ADD [Password] VARCHAR(255) NULL
END

GO

IF EXISTS(
	SELECT * FROM INFORMATION_SCHEMA.COLUMNS
	WHERE TABLE_NAME = 'User'
	AND COLUMN_NAME = 'Password'
	AND IS_NULLABLE = 'YES'
)
BEGIN
	UPDATE [User]
	SET [Password] = '62c8ad0a15d9d1ca38d5dee762a16e01'--1234qwer
	WHERE [Password] IS NULL

	ALTER TABLE [User] ALTER COLUMN [Password] VARCHAR(255) NOT NULL
END