PRINT 'User.1.sql...'

GO

IF NOT EXISTS(
	SELECT * FROM INFORMATION_SCHEMA.COLUMNS
	WHERE TABLE_NAME = 'User' AND COLUMN_NAME = 'Nombre'
)
BEGIN
	ALTER TABLE [User] ADD [Nombre] VARCHAR(50) NULL
END

GO

IF EXISTS(
	SELECT * FROM INFORMATION_SCHEMA.COLUMNS
	WHERE TABLE_NAME = 'User' AND COLUMN_NAME = 'Nombre' AND IS_NULLABLE = 'YES'
)
BEGIN 
	EXEC('
		UPDATE [User] 
		SET Nombre = (SELECT TOP(1) Username FROM [USER])
		WHERE Nombre IS NULL
	')
END

GO

IF EXISTS(
	SELECT * FROM INFORMATION_SCHEMA.COLUMNS
	WHERE TABLE_NAME = 'User' AND COLUMN_NAME = 'Nombre' AND IS_NULLABLE = 'YES'
)
BEGIN	
	EXEC('
		ALTER TABLE [User] ALTER COLUMN [Nombre] VARCHAR(50) NOT NULL
	')
END

GO

--Paterno
IF NOT EXISTS(
	SELECT * FROM INFORMATION_SCHEMA.COLUMNS
	WHERE TABLE_NAME = 'User' AND COLUMN_NAME = 'ApellidoPaterno'
)
BEGIN
	ALTER TABLE [User] ADD [ApellidoPaterno] VARCHAR(50) NULL
END

GO

IF EXISTS(
	SELECT * FROM INFORMATION_SCHEMA.COLUMNS
	WHERE TABLE_NAME = 'User' AND COLUMN_NAME = 'ApellidoPaterno' AND IS_NULLABLE = 'YES'
)
BEGIN 
	EXEC('
		UPDATE [User] 
		SET ApellidoPaterno = (SELECT TOP(1) Username FROM [USER])
		WHERE ApellidoPaterno IS NULL
	')
END

GO

IF EXISTS(
	SELECT * FROM INFORMATION_SCHEMA.COLUMNS
	WHERE TABLE_NAME = 'User' AND COLUMN_NAME = 'ApellidoPaterno' AND IS_NULLABLE = 'YES'
)
BEGIN	
	EXEC('
		ALTER TABLE [User] ALTER COLUMN [ApellidoPaterno] VARCHAR(50) NOT NULL
	')
END

GO

--Materno
IF NOT EXISTS(
	SELECT * FROM INFORMATION_SCHEMA.COLUMNS
	WHERE TABLE_NAME = 'User' AND COLUMN_NAME = 'ApellidoMaterno'
)
BEGIN
	ALTER TABLE [User] ADD [ApellidoMaterno] VARCHAR(50) NULL
END

GO

IF EXISTS(
	SELECT * FROM INFORMATION_SCHEMA.COLUMNS
	WHERE TABLE_NAME = 'User' AND COLUMN_NAME = 'ApellidoMaterno' AND IS_NULLABLE = 'YES'
)
BEGIN 
	EXEC('
		UPDATE [User] 
		SET ApellidoMaterno = (SELECT TOP(1) Username FROM [USER])
		WHERE ApellidoMaterno IS NULL
	')
END

GO

IF EXISTS(
	SELECT * FROM INFORMATION_SCHEMA.COLUMNS
	WHERE TABLE_NAME = 'User' AND COLUMN_NAME = 'ApellidoMaterno' AND IS_NULLABLE = 'YES'
)
BEGIN	
	EXEC('
		ALTER TABLE [User] ALTER COLUMN [ApellidoMaterno] VARCHAR(50) NOT NULL
	')
END

GO

--Email
IF NOT EXISTS(
	SELECT * FROM INFORMATION_SCHEMA.COLUMNS
	WHERE TABLE_NAME = 'User' AND COLUMN_NAME = 'Email'
)
BEGIN
	ALTER TABLE [User] ADD [Email] VARCHAR(50) NULL
END

GO

IF EXISTS(
	SELECT * FROM INFORMATION_SCHEMA.COLUMNS
	WHERE TABLE_NAME = 'User' AND COLUMN_NAME = 'Email' AND IS_NULLABLE = 'YES'
)
BEGIN 
	EXEC('
		UPDATE [User] 
		SET Email = (SELECT TOP(1) Username FROM [USER])
		WHERE Email IS NULL
	')
END

GO

IF EXISTS(
	SELECT * FROM INFORMATION_SCHEMA.COLUMNS
	WHERE TABLE_NAME = 'User' AND COLUMN_NAME = 'Email' AND IS_NULLABLE = 'YES'
)
BEGIN	
	EXEC('
	ALTER TABLE [User] ALTER COLUMN [Email] VARCHAR(50) NOT NULL
	')
END

GO

IF NOT EXISTS(
	SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
	WHERE CONSTRAINT_NAME = 'UQ_UserName' AND CONSTRAINT_TYPE = 'UNIQUE'
)
BEGIN
	ALTER TABLE [User]
	ADD CONSTRAINT UQ_UserName
	UNIQUE (Username);
END

GO