CREATE TABLE [dbo].[Participante]
(
	[IdParticipante] INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	[Nombre] VARCHAR(50) NOT NULL,
	[ApellidoPaterno] VARCHAR(50) NOT NULL,
	[ApellidoMaterno] VARCHAR(50) NULL,
	[FechaNacimiento] DATE NOT NULL,
	[Edad] INT NULL,
	[Domicilio] VARCHAR(255) NOT NULL,
	[Invitado] VARCHAR(2) NOT NULL,
	[NumeroAccion] INT NOT NULL,
	[Telefono] VARCHAR(12) NULL,
	[Email] VARCHAR(100) NULL,
	[TelefonoEmergencia] VARCHAR(12) NULL,
	[IdEquipo] INT NULL  FOREIGN KEY REFERENCES [Equipo](IdEquipo),
	[Socio] VARCHAR(100) NULL,
	[TransactionNumber] VARCHAR(MAX) NULL,
	[StatusPaypal] VARCHAR(MAX),
	[Club] VARCHAR(50) NULL,
	[Folio] INT NOT NULL,
	[Generic01] VARCHAR(255) NULL,
	[Generic02] VARCHAR(255) NULL,
	[Generic03] VARCHAR(255) NULL,
	[Generic04] VARCHAR(255) NULL,
	[Generic05] VARCHAR(255) NULL,
	[Generic06] VARCHAR(255) NULL,
	[Generic07] VARCHAR(255) NULL,
	[Generic08] VARCHAR(255) NULL,
	[Generic09] VARCHAR(255) NULL,
	[Generic10] VARCHAR(255) NULL,
	[FechaRegistro] DATETIME NOT NULL,
	[FechaPago] DATETIME NULL
)
